/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminStudentManagement.java
 *
 * Created on Jan 17, 2011, 7:53:13 PM
 */
package iSUI;

import iSEngine.Sniffer;
import iSUI.Panals.TCPView;
import iSUI.Panals.GeneralView;
import iSUI.Panals.ICMPView;
import iSUI.Panals.IP4View;
import iSUI.Panals.SendView;
import java.awt.CardLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Administrator
 */
public class MailManager extends javax.swing.JFrame {

    private String general = "GENERAL";
    private String tcp = "TCP";
    private String ip = "IP";
    private String icmp = "ICMP";
    private String send = "SEND";
    
    private GeneralView generalView;
    private IP4View ipView;
    private TCPView tcpView;
    private ICMPView icmpView;
    private SendView sendView;
    private Sniffer sniffer;

    /** Creates new form AdminStudentManagement */
    public MailManager() {
        try {
            initComponents();
            this.setTitle("iSniffer");
            setIconImage(ImageIO.read(getClass().getResource("/Resources/browse_spam.png")));
            this.setLocationRelativeTo(this);
        } catch (IOException ex) {
            Logger.getLogger(WelcomeScreen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        this.generalView = new GeneralView();
        this.ipView = new IP4View();
        this.tcpView = new TCPView();
        this.icmpView = new ICMPView();
        this.sendView = new SendView();
        
        
        this.sniffer = new Sniffer();
        this.sniffer.addObserver(this.tcpView);
        this.sniffer.addObserver(this.ipView);
        this.sniffer.addObserver(this.icmpView);
        
        this.generalView.setManger(this);
        this.generalView.setSniffer(this.sniffer);
        this.sendView.setSniffer(this.sniffer);

        this.cardLayoutSetter();
        new Thread(this.sniffer).start(); 
        
    }

    private void cardLayoutSetter() {
        this.jPanelmainpanal.setLayout(new CardLayout());
        this.jPanelmainpanal.add(generalView, general);
        this.jPanelmainpanal.add(ipView, ip);
        this.jPanelmainpanal.add(tcpView, tcp);
        this.jPanelmainpanal.add(icmpView, icmp);
        this.jPanelmainpanal.add(sendView, send);

        //initial panel is set to view panel
        this.panelChange(general);
    }
    
    public void setAllButtonsEnable(){
        this.jButtonIp.setEnabled(true);
        this.jButtontcp.setEnabled(true);
        this.jButtonsend.setEnabled(true);
        this.jButtonicmp.setEnabled(true);
    }

    private void panelChange(String panelName) {
        CardLayout cl = (CardLayout) (jPanelmainpanal.getLayout());
        cl.show(jPanelmainpanal, panelName);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelStudentManagement = new javax.swing.JPanel();
        jPanelSidebar = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtongeneral = new javax.swing.JButton();
        jButtonIp = new javax.swing.JButton();
        jButtonexit = new javax.swing.JButton();
        jButtontcp = new javax.swing.JButton();
        jButtonsend = new javax.swing.JButton();
        jButtonicmp = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelmainpanal = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Spam Filter Manager");

        jPanelSidebar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Action"));

        jButtongeneral.setText("General");
        jButtongeneral.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtongeneral.setFocusable(false);
        jButtongeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtongeneralActionPerformed(evt);
            }
        });

        jButtonIp.setText("IP4");
        jButtonIp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonIp.setEnabled(false);
        jButtonIp.setFocusable(false);
        jButtonIp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIpActionPerformed(evt);
            }
        });

        jButtonexit.setText("Exit");
        jButtonexit.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonexit.setFocusable(false);
        jButtonexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonexitActionPerformed(evt);
            }
        });

        jButtontcp.setText("TCP");
        jButtontcp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtontcp.setEnabled(false);
        jButtontcp.setFocusable(false);
        jButtontcp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontcpActionPerformed(evt);
            }
        });

        jButtonsend.setText("Send");
        jButtonsend.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsend.setEnabled(false);
        jButtonsend.setFocusable(false);
        jButtonsend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsendActionPerformed(evt);
            }
        });

        jButtonicmp.setText("ICMP");
        jButtonicmp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonicmp.setEnabled(false);
        jButtonicmp.setFocusable(false);
        jButtonicmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonicmpActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtongeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtontcp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtonexit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtonsend, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtonIp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(jButtonicmp, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtongeneral)
                .addGap(18, 18, 18)
                .addComponent(jButtontcp)
                .addGap(18, 18, 18)
                .addComponent(jButtonicmp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonIp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jButtonsend)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonexit)
                .addGap(37, 37, 37))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/browse_spam.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSidebarLayout = new javax.swing.GroupLayout(jPanelSidebar);
        jPanelSidebar.setLayout(jPanelSidebarLayout);
        jPanelSidebarLayout.setHorizontalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSidebarLayout.createSequentialGroup()
                .addGroup(jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelSidebarLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel2))
                    .addGroup(jPanelSidebarLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanelSidebarLayout.setVerticalGroup(
            jPanelSidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelSidebarLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        javax.swing.GroupLayout jPanelmainpanalLayout = new javax.swing.GroupLayout(jPanelmainpanal);
        jPanelmainpanal.setLayout(jPanelmainpanalLayout);
        jPanelmainpanalLayout.setHorizontalGroup(
            jPanelmainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 747, Short.MAX_VALUE)
        );
        jPanelmainpanalLayout.setVerticalGroup(
            jPanelmainpanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelStudentManagementLayout = new javax.swing.GroupLayout(jPanelStudentManagement);
        jPanelStudentManagement.setLayout(jPanelStudentManagementLayout);
        jPanelStudentManagementLayout.setHorizontalGroup(
            jPanelStudentManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStudentManagementLayout.createSequentialGroup()
                .addComponent(jPanelSidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelmainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelStudentManagementLayout.setVerticalGroup(
            jPanelStudentManagementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelmainpanal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSidebar, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        jMenuItemexit.setText("Exit");
        jMenuItemexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemexitActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemexit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelStudentManagement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelStudentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemexitActionPerformed

    private void jButtonIpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIpActionPerformed
        this.panelChange(ip);
    }//GEN-LAST:event_jButtonIpActionPerformed

    private void jButtongeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtongeneralActionPerformed
        this.panelChange(general);
    }//GEN-LAST:event_jButtongeneralActionPerformed

    private void jButtonexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonexitActionPerformed

    private void jButtontcpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontcpActionPerformed
        this.panelChange(tcp);
    }//GEN-LAST:event_jButtontcpActionPerformed

    private void jButtonsendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsendActionPerformed
        this.panelChange(send);
    }//GEN-LAST:event_jButtonsendActionPerformed

    private void jButtonicmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonicmpActionPerformed
        this.panelChange(icmp);
    }//GEN-LAST:event_jButtonicmpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MailManager().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIp;
    private javax.swing.JButton jButtonexit;
    private javax.swing.JButton jButtongeneral;
    private javax.swing.JButton jButtonicmp;
    private javax.swing.JButton jButtonsend;
    private javax.swing.JButton jButtontcp;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemexit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelSidebar;
    private javax.swing.JPanel jPanelStudentManagement;
    private javax.swing.JPanel jPanelmainpanal;
    // End of variables declaration//GEN-END:variables
}
