/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AdminStdView.java
 *
 * Created on Jan 17, 2011, 9:35:21 PM
 */

package iSUI.Panals;

import iSEngine.Sniffer;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class SendView extends javax.swing.JPanel {
    
    private Sniffer sniffer;
   
    /** Creates new form AdminStdView */
    public SendView() {
        initComponents();
//        this.debuggerData();
    }
    
    public void setSniffer(Sniffer sniffer){
        this.sniffer = sniffer;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jPanelcomposemail = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSrcIP = new javax.swing.JTextField();
        jTextFieldSrcPort = new javax.swing.JTextField();
        jTextFieldDestIp = new javax.swing.JTextField();
        jTextFieldbDestPort = new javax.swing.JTextField();
        jTextFieldAckNum = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaData = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jButtonsendmail = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder("Send"));

        jLabel10.setFont(new java.awt.Font("Papyrus", 1, 24));
        jLabel10.setText("Send TCP Packet");

        jLabel1.setText("Src. Domain");

        jLabel2.setText("Src. Port");

        jLabel3.setText("Dest. Domain");

        jLabel4.setText("Dest. Port");

        jLabel5.setText("Ack. Num");

        jTextFieldSrcPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSrcPortActionPerformed(evt);
            }
        });

        jTextFieldbDestPort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldbDestPortActionPerformed(evt);
            }
        });

        jTextAreaData.setColumns(20);
        jTextAreaData.setRows(5);
        jScrollPane1.setViewportView(jTextAreaData);

        jLabel6.setText("Data");

        javax.swing.GroupLayout jPanelcomposemailLayout = new javax.swing.GroupLayout(jPanelcomposemail);
        jPanelcomposemail.setLayout(jPanelcomposemailLayout);
        jPanelcomposemailLayout.setHorizontalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldSrcIP, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldDestIp)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldbDestPort)
                    .addComponent(jTextFieldSrcPort, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(217, 217, 217)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldAckNum, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addGap(234, 234, 234))
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanelcomposemailLayout.setVerticalGroup(
            jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                        .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFieldSrcIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldDestIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelcomposemailLayout.createSequentialGroup()
                        .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldSrcPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldbDestPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))))
                .addGap(32, 32, 32)
                .addGroup(jPanelcomposemailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldAckNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jButtonsendmail.setText("Send");
        jButtonsendmail.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonsendmail.setFocusable(false);
        jButtonsendmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsendmailActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelcomposemail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButtonclear, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 407, Short.MAX_VALUE)
                        .addComponent(jButtonsendmail, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(227, 227, 227))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelcomposemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonsendmail)
                    .addComponent(jButtonclear))
                .addContainerGap(16, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonsendmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsendmailActionPerformed
         this.composeMail();
    }//GEN-LAST:event_jButtonsendmailActionPerformed

    private void composeMail(){
        try {
            
            InetAddress srcip = InetAddress.getByName("www.microsoft.com");
            int srcprt = 14;
            InetAddress destip = InetAddress.getByName("www.google.com");
            int destprt = 34;
            short ack = 78;
            String data = "You are hacked! ZUCKER!!!";
            
            if(!"".equals(this.jTextFieldSrcIP.getText())){
                srcip = InetAddress.getByName(this.jTextFieldSrcIP.getText());
            }
            
            if(!"".equals(this.jTextFieldDestIp.getText())){
                destip = InetAddress.getByName(this.jTextFieldDestIp.getText());
            }
            
            if(!"".equals(this.jTextFieldSrcPort.getText())){
                srcprt = Integer.parseInt(this.jTextFieldSrcPort.getText());
            }
            
            if(!"".equals(this.jTextFieldbDestPort.getText())){
                destprt = Integer.parseInt(this.jTextFieldbDestPort.getText());
            }
            
            if(!"".equals(this.jTextFieldAckNum.getText())){
                ack = Short.parseShort(this.jTextFieldAckNum.getText());
            }
            
            if(!"".equals(this.jTextAreaData.getText())){
                data = (this.jTextAreaData.getText());
            }
            
            if(this.sniffer.sendPacket(srcip, destip, srcprt, destprt, ack, data)){
                JOptionPane.showMessageDialog(null, "Packet Send Successfully.");
                this.clearAll();
            }else{
                JOptionPane.showMessageDialog(null, "Packet Sending Failed.");
            }
            
        } catch (UnknownHostException ex) {
            Logger.getLogger(SendView.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
//    private boolean validateMail(String emailAddress){
//        Pattern rfc2822 = Pattern.compile(
//                "www.[a-z0-9-]*.com"
//        );
//
//        if (rfc2822.matcher(emailAddress).matches()) {
//            return true;
//        }else{
//            return false;
//        }
//    }
    
    private void jTextFieldbDestPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldbDestPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldbDestPortActionPerformed

    private void jTextFieldSrcPortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSrcPortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSrcPortActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        this.clearAll();
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void clearAll(){
        this.jTextFieldAckNum.setText("");
        this.jTextFieldDestIp.setText("");
        this.jTextFieldSrcIP.setText("");
        this.jTextFieldSrcPort.setText("");
        this.jTextFieldbDestPort.setText("");
        this.jTextAreaData.setText("");
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtonsendmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanelcomposemail;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaData;
    private javax.swing.JTextField jTextFieldAckNum;
    private javax.swing.JTextField jTextFieldDestIp;
    private javax.swing.JTextField jTextFieldSrcIP;
    private javax.swing.JTextField jTextFieldSrcPort;
    private javax.swing.JTextField jTextFieldbDestPort;
    // End of variables declaration//GEN-END:variables

}
